- name: configure backend server
  hosts: backend
  become: yes
  tasks:
    - name: disable current nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - mysql

    - name: create expense user
      ansible.builtin.user:
        name: expense

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download backend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip

    - name: unzip backend code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes # ansible by default thinks src is in ansible control machine
        # # Indicates that the source file is on the remote server(nodes), not the local machine

    - name: Install dependencies
      community.general.npm:
        path: /app

    - name: copy backend service
      ansible.builtin.copy:
        src: backend.service # here, this file is present control machine, so will are not giving - remote_src: yes
        dest: /etc/systemd/system/backend.service

    - name: install python libs
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9 #executable parameter specifies which Python interpreter or pip executable to use when installing the packages.
      loop:
        - cryptography
        - PyMySQL

    #executable: pip3.9 tells Ansible to use pip3.9 instead of the default pip

    - name: import mysql data
      community.mysql.mysql_db:
        state: import
        name: all # name parameter typically refers to the name of the MySQL database
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql.daws82s.online
        target: /app/schema/backend.sql

    - name: daemon reload and restart service
      ansible.builtin.systemd_service:
        enabled: true
        state: restarted
        daemon_reload: true
        name: backend
